version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install haml
          command: gem install haml
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Build
          command: npm run-script build
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
workflows:
  version: 2
  build:
    jobs:
      - build