name: Node.js CI

on:
  push:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: npx webpack
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        path: 'dist/*.zip'
