name: Artifacts

on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: npx webpack
    - name: Upload Chrome Artifact
      uses: actions/upload-artifact@v2
      with:
        name: 'metro-start-chrome'
        path: 'dist/*chrome.zip'
    - name: Upload Firefox Artifact
      uses: actions/upload-artifact@v2
      with:
        name: 'metro-start-firefox'
        path: 'dist/*firefox.zip'
